export const BIBLE_BOOKS = [
  { slug: 'genesis', name: 'Génesis', testament: 'at', chapters: 50 },
  { slug: 'exodo', name: 'Éxodo', testament: 'at', chapters: 40 },
  { slug: 'levitico', name: 'Levítico', testament: 'at', chapters: 27 },
  { slug: 'numeros', name: 'Números', testament: 'at', chapters: 36 },
  { slug: 'deuteronomio', name: 'Deuteronomio', testament: 'at', chapters: 34 },
  { slug: 'josue', name: 'Josué', testament: 'at', chapters: 24 },
  { slug: 'jueces', name: 'Jueces', testament: 'at', chapters: 21 },
  { slug: 'rut', name: 'Rut', testament: 'at', chapters: 4 },
  { slug: '1-samuel', name: '1 Samuel', testament: 'at', chapters: 31 },
  { slug: '2-samuel', name: '2 Samuel', testament: 'at', chapters: 24 },
  { slug: '1-reyes', name: '1 Reyes', testament: 'at', chapters: 22 },
  { slug: '2-reyes', name: '2 Reyes', testament: 'at', chapters: 25 },
  { slug: '1-cronicas', name: '1 Crónicas', testament: 'at', chapters: 29 },
  { slug: '2-cronicas', name: '2 Crónicas', testament: 'at', chapters: 36 },
  { slug: 'esdras', name: 'Esdras', testament: 'at', chapters: 10 },
  { slug: 'nehemias', name: 'Nehemías', testament: 'at', chapters: 13 },
  { slug: 'ester', name: 'Ester', testament: 'at', chapters: 10 },
  { slug: 'job', name: 'Job', testament: 'at', chapters: 42 },
  { slug: 'salmos', name: 'Salmos', testament: 'at', chapters: 150 },
  { slug: 'proverbios', name: 'Proverbios', testament: 'at', chapters: 31 },
  { slug: 'eclesiastes', name: 'Eclesiastés', testament: 'at', chapters: 12 },
  { slug: 'cantares', name: 'Cantares', testament: 'at', chapters: 8 },
  { slug: 'isaias', name: 'Isaías', testament: 'at', chapters: 66 },
  { slug: 'jeremias', name: 'Jeremías', testament: 'at', chapters: 52 },
  { slug: 'lamentaciones', name: 'Lamentaciones', testament: 'at', chapters: 5 },
  { slug: 'ezequiel', name: 'Ezequiel', testament: 'at', chapters: 48 },
  { slug: 'daniel', name: 'Daniel', testament: 'at', chapters: 12 },
  { slug: 'oseas', name: 'Oseas', testament: 'at', chapters: 14 },
  { slug: 'joel', name: 'Joel', testament: 'at', chapters: 3 },
  { slug: 'amos', name: 'Amós', testament: 'at', chapters: 9 },
  { slug: 'abdias', name: 'Abdías', testament: 'at', chapters: 1 },
  { slug: 'jonas', name: 'Jonás', testament: 'at', chapters: 4 },
  { slug: 'miqueas', name: 'Miqueas', testament: 'at', chapters: 7 },
  { slug: 'nahum', name: 'Nahúm', testament: 'at', chapters: 3 },
  { slug: 'habacuc', name: 'Habacuc', testament: 'at', chapters: 3 },
  { slug: 'sofonias', name: 'Sofonías', testament: 'at', chapters: 3 },
  { slug: 'hageo', name: 'Hageo', testament: 'at', chapters: 2 },
  { slug: 'zacarias', name: 'Zacarías', testament: 'at', chapters: 14 },
  { slug: 'malaquias', name: 'Malaquías', testament: 'at', chapters: 4 },
  { slug: 'mateo', name: 'Mateo', testament: 'nt', chapters: 28 },
  { slug: 'marcos', name: 'Marcos', testament: 'nt', chapters: 16 },
  { slug: 'lucas', name: 'Lucas', testament: 'nt', chapters: 24 },
  { slug: 'juan', name: 'Juan', testament: 'nt', chapters: 21 },
  { slug: 'hechos', name: 'Hechos', testament: 'nt', chapters: 28 },
  { slug: 'romanos', name: 'Romanos', testament: 'nt', chapters: 16 },
  { slug: '1-corintios', name: '1 Corintios', testament: 'nt', chapters: 16 },
  { slug: '2-corintios', name: '2 Corintios', testament: 'nt', chapters: 13 },
  { slug: 'galatas', name: 'Gálatas', testament: 'nt', chapters: 6 },
  { slug: 'efesios', name: 'Efesios', testament: 'nt', chapters: 6 },
  { slug: 'filipenses', name: 'Filipenses', testament: 'nt', chapters: 4 },
  { slug: 'colosenses', name: 'Colosenses', testament: 'nt', chapters: 4 },
  { slug: '1-tesalonicenses', name: '1 Tesalonicenses', testament: 'nt', chapters: 5 },
  { slug: '2-tesalonicenses', name: '2 Tesalonicenses', testament: 'nt', chapters: 3 },
  { slug: '1-timoteo', name: '1 Timoteo', testament: 'nt', chapters: 6 },
  { slug: '2-timoteo', name: '2 Timoteo', testament: 'nt', chapters: 4 },
  { slug: 'tito', name: 'Tito', testament: 'nt', chapters: 3 },
  { slug: 'filemon', name: 'Filemón', testament: 'nt', chapters: 1 },
  { slug: 'hebreos', name: 'Hebreos', testament: 'nt', chapters: 13 },
  { slug: 'santiago', name: 'Santiago', testament: 'nt', chapters: 5 },
  { slug: '1-pedro', name: '1 Pedro', testament: 'nt', chapters: 5 },
  { slug: '2-pedro', name: '2 Pedro', testament: 'nt', chapters: 3 },
  { slug: '1-juan', name: '1 Juan', testament: 'nt', chapters: 5 },
  { slug: '2-juan', name: '2 Juan', testament: 'nt', chapters: 1 },
  { slug: '3-juan', name: '3 Juan', testament: 'nt', chapters: 1 },
  { slug: 'judas', name: 'Judas', testament: 'nt', chapters: 1 },
  { slug: 'apocalipsis', name: 'Apocalipsis', testament: 'nt', chapters: 22 },
];

export const BOOKS_BY_SLUG = Object.fromEntries(BIBLE_BOOKS.map((book) => [book.slug, book]));

export function getBookBySlug(slug) {
  return BOOKS_BY_SLUG[slug] || null;
}

export function chapterReference(slug, chapter) {
  const book = getBookBySlug(slug);
  if (!book) return null;
  return `${book.name} ${chapter}`;
}
